name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant permissions and Build APK
        run: |
          DIR=$(dirname $(find . -maxdepth 3 -name "gradlew" | head -n 1))
          echo "Building in $DIR"
          cd "$DIR"
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: teleguest-app
          path: '**/build/outputs/apk/debug/*.apk'
